### ISSUE TITLE
Kotlin 1.8.22 support

### ISSUE THREAD

**Issue by kurteous** [jeppeman/mockposable#11]
Hi! My colleague @ricardomgarciaf requested Kotlin 1.8.21 support recently. Thanks for providing such a quick turnaround for his request!

Now that Kotlin 1.8.22 is out I'm hoping you can update to this latest bug fix version as well. Thanks.

**Comment by jeppeman** [comment]
Hi! Thanks for reporting. I've published a snapshot now, would you mind verifying whether it works on your end?
Version: `0.5-SNAPSHOT`.
Remember to add the sonatype snapshot repository:

```groovy
maven { 
    url 'https://oss.sonatype.org/content/repositories/snapshots/'
}
```

**Comment by kurteous** [comment]
> Hi! Thanks for reporting. I've published a snapshot now, would you mind verifying whether it works on your end? Version: `0.5-SNAPSHOT`. Remember to add the sonatype snapshot repository:
> 
> ```groovy
> maven { 
>     url 'https://oss.sonatype.org/content/repositories/snapshots/'
> }
> ```

Thanks! Will try it out now.

**Comment by kurteous** [comment]
Hi! I am still working through a range of test failures to determine if they are specific to mockposable or more generally caused by updating to Kotlin 1.8.22 and updating compose. I'll let you know as soon as I figure it out.

**Comment by kurteous** [comment]
@jeppeman Thanks for your patience. Our failing tests appear to be due to the same issue reported here: https://github.com/mockk/mockk/issues/1094
`kotlinx-coroutines` was updated to `1.7.0` in kotlin `1.8.22`, and now tests that were previously succeeding are failing. In our case we're seeing exceptions that were apparently swallowed or not caught by `runTest` now being caught and causing tests to fail. I'm guessing it's possible to fix the tests, but that's going to take some time to explore. 

That all being said, the few tests that use `mockposable` are working great! So I think you can say that your latest version is good, for us anyway.

**Comment by jeppeman** [comment]
@kurteous thanks for the investigation - hope the issue with MockK gets resolved. 
Closing this now as `0.5` is available on mavenCentral.
Appreciate the report, let me know if you run into other problems.
