### ISSUE TITLE
Kotlin 1.9.0 / Compose compiler 1.5.1 support

### ISSUE THREAD

**Issue by kurteous** [jeppeman/mockposable#13]
Hi,

Thanks for updating to 1.8.22. Any chance you can provide another update, this time to 1.9.0 with Compose compiler 1.5.1? Thanks!

**Comment by jeppeman** [comment]
Hey @kurteous, I've published version `0.6`, it should support 1.9.0 / 1.5.1.

**Comment by kurteous** [comment]
> Hey @kurteous, I've published version `0.6`, it should support 1.9.0 / 1.5.1.

Thank you so much, as always!
