### ISSUE TITLE
"Composition is disposed while composing" Error when Running JUnit Tests

### ISSUE THREAD

**Issue by hscissors** [jeppeman/mockposable#16]
Compose 1.5.0
Compose Compiler 1.5.1
Mockposable 0.6

I running into an odd error while running tests:
```
Composition is disposed while composing. If dispose is triggered by a call in @Composable function, consider wrapping it with SideEffect block. java.lang.IllegalStateException: Composition is disposed while composing. If dispose is triggered by a call in @Composable function, consider wrapping it with SideEffect block.
```

For context, the failing mock compose calls are wrapped in other compose calls. For example:

```
class Test() {
    @Composable fun run(): DataModel { ... }
}

class Wrapper() {
    @Composable fun run() {
       Test.run() 
    }
}
```

**Comment by hscissors** [comment]
Never mind, it was an issue with compatible version of Compose being pulled in through other compose-dependant libraries.

**Comment by gaara87** [comment]
I'm facing the exact same issues.

Using the following versions - 

mockposable  = 0.8
compose bom = 2024.04.00
compose-compiler = 1.5.10

Unlike OP, i'm using it with Compose UI, but ultimately the same problem
