### ISSUE TITLE
Kotlin 1.9.22 / Compose compiler 1.5.7 support

### ISSUE THREAD

**Issue by vassilisimon** [jeppeman/mockposable#18]
Hi, 

could you support Kotlin 1.9.22 / Compose compiler 1.5.7?

Thanks!

**Comment by jeppeman** [comment]
Hi, thanks for reporting. I'm om vacation until end of month and can't publish until then unfortunately, I can make a PR when I have some time to spare though, and you could build from that branch in the meantime if that works?

**Comment by robert-schuster-rtl** [comment]
meanwhile the combination

kotlin 1.9.22
compose compiler 1.5.8

popped up (see https://developer.android.com/jetpack/androidx/releases/compose-kotlin)

would be good to support that instead.

**Comment by jeppeman** [comment]
Sorry about the wait @vassilisimon @robert-schuster-rtl. I've published `0.7` now. It support Kotlin 1.9.22 and Compose compiler 1.5.8
