### ISSUE TITLE
Add Gradle configuration option for Compose Compiler version

### ISSUE THREAD

**Issue by jpetitto** [jeppeman/mockposable#20]
I was wondering if it would be possible to add a configuration option that let's us specify the Compose Compiler version for mockposable to use? [Molecule provides the ability to do this](https://github.com/cashapp/molecule?tab=readme-ov-file#custom-compose-compiler), which means both the Kotlin and Compose Compiler versions can be updated without also having to update the library each time.

**Comment by jeppeman** [comment]
Good suggestion @jpetitto, I can look into that in the weekend or early next week. Or if you feel like it you are welcome to submit a PR.

**Comment by jeppeman** [comment]
Apologies for the wait, but I've started working on this now. Should hopefully be done during the day.

**Comment by jeppeman** [comment]
@jpetitto version `0.8` is available now, you can configure the compose compiler version like so:
```groovy
mockposable {
    composeCompilerVersion = "x.y.z"
}
```
