### ISSUE TITLE
Current setup is not very scalable

### ISSUE THREAD

**Issue by gaara87** [jeppeman/mockposable#6]
Consider this module setup for larger projects.
```
Project/
├── lib-mock-tester/
│   ├── build.gradle (this contains apply plugin: "com.jeppeman.mockposable" mockposable { plugins = [] } )
│   └── main/
│       └── CustomTestHelpers.kt (functions that use `everyComposable { }`)
└── feature-a/
    ├── build.gradle (this contains testImplementation(lib-mock-tester) )
    └── test/
        └── FeatureATest.kt
```
^ would currently not be possible as the plugin automatically exposes `everyComposable { }` and other library functions only inside the `test` source set.

What are your thoughts about moving the compiler and/or other parts as dependencies that can be directly used? (rather than just the plugin)

**Comment by jeppeman** [comment]
The compiler and all plugins are exposed as individual artifacts, you can depend on them individually if you want to: https://mvnrepository.com/artifact/com.jeppeman.mockposable

**Comment by gaara87** [comment]
Ah! I was completely blind to the artifacts. Thanks for highlighting them. 

I was able to pull down the artifacts individually into `lib-mock-tester` module, but I'm a little bit confused how to have the compiler process that does the transformation trigger, even if I include `implementation("com.jeppeman.mockposable:mockposable-compiler:0.2")`

Do I have to do something similar to `MockposableSubPlugin`?

**Comment by jeppeman** [comment]
> Do I have to do something similar to MockposableSubPlugin?

Yes, that is the easiest way since we have to pass arguments to the compiler plugin, it is possible by adding the plugin to the classpath (similar to [here](https://github.com/jeppeman/mockposable/blob/main/mockposable/mockposable-runtime/mockposable-runtime-mockk/build.gradle.kts#L23) and passing arguments manullay. But much simpler to register through the `SubPlugin`-mechanism.
