### ISSUE TITLE
Kotlin 1.8.21 support

### ISSUE THREAD

**Issue by ricardomgarciaf** [jeppeman/mockposable#9]
Hello! 
I'm trying to use mockposable in my project, but I'm having issues since my project is using Kotlin 1.8.21 while latest current mockposable release (0.3) is using 1.8.10. I'm getting following message `This version (1.4.4) of the Compose Compiler requires Kotlin version 1.8.10 but you appear to be using Kotlin version 1.8.20 which is not known to be compatible.`.
Do you think it would be possible to have a new release that adds support for 1.8.21?

**Comment by jeppeman** [comment]
Hey!
Thanks for reporting. Yes, I'll try to get it done during the day sometime. 
I'll get back to you.

**Comment by jeppeman** [comment]
@ricardomgarciaf I've published a snapshot version now, can you verify that it works? `0.4-SNAPSHOT`

Make sure to include the snapshot repo:

```groovy
buildscript {
    repositories {
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
}
```

**Comment by ricardomgarciaf** [comment]
Thanks for the quick response! I believe I've followed all required steps, but I'm getting `Could not find com.jeppeman.mockposable:mockposable-compiler:0.4-SNAPSHOT.` Could you double-check on your side?

**Comment by jeppeman** [comment]
It's there, https://oss.sonatype.org/content/repositories/snapshots/com/jeppeman/mockposable/mockposable-compiler/0.4-SNAPSHOT/

Are you sure you've included the repo in `buildscript`?  Or alternatively in `pluginManagement`

**Comment by ricardomgarciaf** [comment]
The issue was on my end. Looks good now! Thank you.

**Comment by jeppeman** [comment]
@ricardomgarciaf thanks for verifying. I will publish to mavenCentral now then, `0.4` should be available in an hour or so.
